#!/bin/sh

# include library helps for colorized echo
source ./lib_sh/echos.sh

# Update macOS software first off
info 'updating macOS software first'
sudo softwareupdate -i -a

info 'configuring macOS settings'

# Creating githubt directory
mkdir -p "$HOME/Documents/github/"

if source ${HOME}/.dotfiles/macos/set-defaults | while read -r data; do info "$data"; done
then
	  success "done"
else
	  fail "macOS settings failed"
fi
