#!/usr/bin/env bash
#
# Install all applications and run install.sh in every subdir

set -e

cd "$(dirname $0)"/..

# # Create LaunchAgents directory so Amazon Music installs
# info "patching for amazon music install"
# mkdir -p ~/Library/LaunchAgents
# sudo chown -R $USER ~/Library/LaunchAgents
# sudo chmod 755 ~/Library/LaunchAgents

# Run Homebrew through the Brewfile
info "installing brew bundle"
brew bundle
success "brew bundle complete"

# Change shell to ZSH, if it isn't already there
if grep -Fxq /etc/shells '/usr/local/bin/zsh'
then
	info "zsh already set in /etc/shells"
else
	sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells" && chsh -s /usr/local/bin/zsh
	success "zsh shell set as default"
fi

success 'setup is complete'
