#!/usr/bin/env bash

# include library helps for colorized echo
source ./lib_sh/echos.sh

# set root directory for dotfiles install/symlinks
cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user '›› What is your github author name?'
    read -e git_authorname
    user '›› What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    # add git alias (cmp) to add, commit with message and push
    # usage: git cmp "long commit message"
    git config --global alias.cmp '!f() { git add -A && git commit -m "$@" && git push; }; f'

    success 'gitconfig'
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig
install_dotfiles

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 120; kill -0 "$$" || exit; done 2>/dev/null &

# install homebrew and cask
info "installing homebrew"
if source homebrew/install | while read -r data; do info "$data"; done
then
  success "homebrew installed"
else
  fail "error installing homebrew"
fi

read -p "Press ENTER to continue..."

# begin install of applications via Homebrew
if source script/appinstall | while read -r data; do info "$data"; done
then
	success "application install complete"
else
	fail "error brewing"
fi

# Forcing order of installation
# macOS settings
if source macos/install | while read -r data; do info "$data"; done
then
	success "macOS settings complete"
else
	fail "error configuring macOS"
fi

# install custom applications
if source apps/install | while read -r data; do info "$data"; done
then
	success "custom applications installed"
else
	fail "error installing applications"
fi

# configure atom
if source atom/install | while read -r data; do info "$data"; done
then
	success "custom applications installed"
else
	fail "error installing applications"

# configure ssh
if source ssh/install | while read -r data; do info "$data"; done
then
	success "custom applications installed"
else
	fail "error installing applications"
fi

# final clean-up
if source post-proc/install | while read -r data; do info "$data"; done
then
	success "finalize installation"
else
	fail "error finalizing installation"

echo ''
success '  All installed!'
