#!/usr/bin/env bash

# ~/osx.sh — Originally from https://mths.be/osx

# include library helps for colorized echo
source ./lib_sh/echos.sh

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `osx.sh` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Remove all icons from the Dock
dockutil --remove all

# Add prferred apps
dockutil --add "/Applications/Safari.app/"
dockutil --add "/Applications/Firefox.app/"
dockutil --add "/Applications/Calendar.app/"
dockutil --add "/Applications/Contacts.app/"
dockutil --add "/Applications/Reminders.app/"
dockutil --add "/Applications/Messages.app/"
dockutil --add "/Applications/Notes.app/"
dockutil --add "/Applications/Microsoft OneNote.app"
dockutil --add "/Applications/News.app/"
dockutil --add "/Applications/Spotify.app"
dockutil --add "/Applications/Atom.app"
dockutil --add "/Applications/iTerm.app"
dockutil --add "/Applications/Photos.app"
dockutil --add "/Applications" --view grid --display folder --sort name --section others --allhomes
dockutil --add '~/Documents' --view list --display folder --sort name --section others
dockutil --add '~/Downloads' --view list --display folder --sort name --section others
